### ISSUE TITLE
Binary distribution of horizon-loader.exe

### ISSUE THREAD

**Issue by WinterSolstice8** [MattyGWS/HorizonXI-Linux-Installation#2]
Hello,

I work upstream of Horizon (and upstream of ASB for that matter) and I saw you're distributing a horizon-loader.exe binary

`To replace the bootloader, first download this one https://raw.githubusercontent.com/trentondyck/horizon_scripts/main/horizon-loader.exe`

Is this modified from a release shipped by Horizon or carte-blanch copied? Horizon has notice of open source licenses but distributing a modified version of this loader without the source code goes against the license -- as well as natural security implications of course.

If there's a bugfix to be found in this (potentially) modified version I'm sure we would love to take it in, there are so few linux users around.

**Comment by MattyGWS** [comment]
Hi, it's not modified, it's just the working version of the bootloader as there is a bug installing from the old launcher. However people are reporting that we can now skip the step of using the old launcher at the beginning now so I can probably remove the bootloader link entirely if it works now. I still need to test
